package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloApp.idl
* Sábado, 5 de Maio de 2018 13h05min45s BRT
*/

public interface HelloOperations 
{
  String msg ();
  void msg (String newMsg);
} // interface HelloOperations
